# Generated by Django 3.2.16 on 2024-03-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150, verbose_name='Слово')),
                ('term_frequency', models.IntegerField(max_length=100, verbose_name='Частота слова или TF')),
                ('inverse_document_frequency', models.IntegerField(max_length=100, verbose_name='Oбратная частота документа или IDF')),
            ],
            options={
                'verbose_name': 'Слова',
                'verbose_name_plural': 'Слова',
                'ordering': ('-inverse_document_frequency',),
            },
        ),
    ]
