# Generated by Django 3.2.16 on 2024-03-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=150, verbose_name='Назнавние документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150, verbose_name='Слово')),
                ('word_quantity', models.IntegerField(default=0, verbose_name='Количество раз слово встречается в тексте')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='text_recognition.document', verbose_name='Название документа')),
            ],
            options={
                'verbose_name': 'Слова',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='DocumentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_frequency', models.IntegerField(default=0, verbose_name='Частота слова или TF')),
                ('inverse_document_frequency', models.IntegerField(default=0, verbose_name='Oбратная частота документа или IDF')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_recognition.document')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_recognition.text')),
            ],
            options={
                'verbose_name': 'Документ и текст',
                'verbose_name_plural': 'Документы и тексты',
                'ordering': ('-inverse_document_frequency',),
            },
        ),
    ]
