# Generated by Django 3.2.16 on 2024-03-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_recognition', '0002_auto_20240323_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='inverse_document_frequency',
            field=models.IntegerField(blank=True, verbose_name='Oбратная частота документа или IDF'),
        ),
    ]
