# Generated by Django 3.2.16 on 2024-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_recognition', '0002_alter_document_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(max_length=150, verbose_name='Назнавние документа'),
        ),
    ]
