# Generated by Django 3.2.16 on 2024-03-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_recognition', '0003_alter_document_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='total_words',
            field=models.IntegerField(default=0, verbose_name='Количество слов в документе'),
        ),
    ]
