# Generated by Django 3.2.16 on 2024-03-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_recognition', '0004_document_total_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-inverse_document_frequency',), 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='documenttext',
            options={'verbose_name': 'Документ и текст', 'verbose_name_plural': 'Документы и тексты'},
        ),
        migrations.AddField(
            model_name='document',
            name='inverse_document_frequency',
            field=models.IntegerField(default=0, verbose_name='Oбратная частота документа или IDF'),
        ),
        migrations.AddField(
            model_name='document',
            name='term_frequency',
            field=models.IntegerField(default=0, verbose_name='Частота слова или TF'),
        ),
    ]
