# Generated by Django 3.2.16 on 2024-03-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_recognition', '0005_auto_20240324_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='term_frequency',
        ),
        migrations.AddField(
            model_name='text',
            name='term_frequency',
            field=models.IntegerField(default=0, verbose_name='Частота слова или TF'),
        ),
    ]
