# Generated by Django 3.2.16 on 2024-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_recognition', '0007_alter_text_term_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='term_frequency',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Частота слова или TF'),
        ),
    ]
