# Generated by Django 3.2.16 on 2024-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_recognition', '0008_alter_text_term_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='inverse_document_frequency',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Oбратная частота документа или IDF'),
        ),
    ]
