# Generated by Django 3.2.16 on 2024-03-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_recognition', '0009_text_inverse_document_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ('-inverse_document_frequency',), 'verbose_name': 'Слова', 'verbose_name_plural': 'Слова'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='inverse_document_frequency',
        ),
    ]
